version: '3'

services:   
    db:
        image: mariadb
        ports:
            - "3309:3306"
        volumes:
            - "./files/docker/db-dumps/:/docker-entrypoint-initdb.d/"
        env_file: "./files/env/docker.db.env"

        container_name: ${DOCKER_CONTAINER_NAME}_db
        networks:
            - localdev

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "8181:80"
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: wp123456        

        container_name: ${DOCKER_CONTAINER_NAME}_phpmyadmin
        networks:
            - localdev
networks:
  localdev:
    external: true